### ISSUE TITLE
Problema submetido em menos de 1 minuto não foi computado no total de problemas resolvidos.

### ISSUE THREAD

**Issue by lucianovr** [maratona-linux/maratona-animeitor#2]
Parece que se o problema for resolvido em menos de 1 minuto, o tempo dele no BOCA é 0. No score gerado pelo animeitor, esse problema não foi computado como resolvido.

**Comment by oshiro** [comment]
Resover problema em menos de 1 minuto é claramente trapaça, logo o problema não deve ser computado como resolvido. :)
Falando sério, o bug já foi identificado e será corrigido.

**Comment by oshiro** [comment]
Resover problema em menos de 1 minuto é claramente trapaça, logo o problema não deve ser computado como resolvido. :)
Falando sério, o bug já foi identificado e será corrigido.
